# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professorcontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.TextField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='mainWeb.ProffessorData')),
            ],
        ),
    ]
