# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWeb', '0002_auto_20171108_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='userImg',
            field=models.ImageField(default='test/None/no-img.jpg', upload_to='test/%m/%d'),
        ),
    ]
