# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWeb', '0003_auto_20171108_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('makerUser', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('hit_count', models.IntegerField(default=0)),
            ],
        ),
    ]
