# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWeb', '0005_unknowcommnet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unknowcommnet',
            old_name='board',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
