# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainWeb', '0008_ggultipboard_reportboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='messages',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainWeb.Message'),
        ),
    ]
