# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWeb', '0009_auto_20171110_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='senderUser',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
