# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainWeb', '0010_message_senderuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='messages',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainWeb.Message'),
        ),
    ]
