# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWeb', '0012_auto_20171110_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone_num',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='myuser',
            name='school_num',
            field=models.CharField(default='', max_length=50),
        ),
    ]
